### ISSUE TITLE
Manter Administrador 

### ISSUE THREAD

**Issue by weslleysp11** [AndreLFS/aurum#21]
PASSO5: O sistema não apresenta a mensagem de login já existentes e salva no banco de dados.
PASSO6: O sistema não apresenta a mensagem de E-mail incorreto e salva no banco de dados.

**Comment by pedrogabrielfs** [comment]
Problema corrigido, quando o usuario tenta cadastrar com um login ja existente ele aparece um alerta para ele mudar o email
